name: checkrun

on:
  check_run:
    types: [completed]

jobs:
  build:
    name: checkrun
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: hmarr/debug-action@v2
