name: checksuite

on:
  check_suite:
    types: [completed]

jobs:
  build:
    name: checksuite
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: hmarr/debug-action@v2
