name: CI

on:
  workflow_run:
    workflows:
      - 'CI'
    types:
      - 'completed'

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: hmarr/debug-action@v2
