name: CI build

on:
  workflow_run:
    workflows:
      - 'CI'
    types:
      - 'completed'

jobs:
  build:
    name: CI build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: hmarr/debug-action@v2
