name: Build Android

on: [push, pull_request]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      # build dist folder
      - run: mkdir -p dist && echo $(date) > "dist/$(date).txt" && ls -la dist
      - run: git add dist --force
      - run: git status

      # commit and push dist folder
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: CI build
          file_pattern: dist
          add_options: '--force'
