# send notifications to telegram group on commits, releases, issues
# https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/contexts#github-context

name: notifications

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  push:
    # https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28#pushevent
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commit: ${{ github.event.commits }}
    steps:
    - name: debug
      env:
        GITHUB_CONTEXT: ${{ toJSON(matrix.commit) }}
      run: echo "$GITHUB_CONTEXT"

    # write message to file
    - run: echo "<code>${{ matrix.commit.message }}</code>" >> message.txt
    - run: echo "" >> message.txt
    - run: echo "by <i>${{ matrix.commit.author.username }}</i>" >> message.txt
    - run: echo "${{ matrix.commit.url }}" >> message.txt
    - run: date -d "${{ matrix.commit.timestamp }}" +"%d/%m/%y" >> message.txt

    # send message, @plebbit telegram chat id is -1234
    - name: "telegram notification"
      uses: appleboy/telegram-action@master
      with:
        to: 1986059725
        token: ${{ secrets.TELEGRAM_TOKEN }}
        disable_web_page_preview: true
        format: html
        message_file: message.txt
