# send notifications to telegram group on commits, releases, issues
# https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/contexts#github-context

name: notifications

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types: [published]
  issues:
    types: [opened]

jobs:
  push:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        commit: ${{ github.event.commits }}
    steps:
    # - name: debug
    #   env:
    #     DEBUG: ${{ toJSON(matrix.commit) }}
    #   run: echo "$DEBUG"

    # write message to file
    - run: echo "<code>${{ matrix.commit.message }}</code>" >> message.txt
    - run: echo "" >> message.txt
    - run: echo "by <i>${{ matrix.commit.author.username }}</i>" >> message.txt
    - run: echo "${{ matrix.commit.url }}" >> message.txt
    - run: date -d "${{ matrix.commit.timestamp }}" +"%d/%m/%y at %H:%M" >> message.txt

    # send message, @plebbit telegram chat id is -1234
    - name: "telegram notification"
      uses: appleboy/telegram-action@master
      with:
        to: 1986059725
        token: ${{ secrets.TELEGRAM_TOKEN }}
        disable_web_page_preview: true
        format: html
        message_file: message.txt

  release:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-latest
    steps:
    - name: debug
      env:
        DEBUG: ${{ toJSON(github) }}
      run: echo "$DEBUG"

    # write message to file
    - run: echo "<b>${{ github.event.repository.name }} ${{ github.event.release.name }}</b>" >> message.txt
    - run: echo "" >> message.txt
    - run: echo "${{ github.event.release.body }}" >> message.txt
    - run: echo "${{ github.event.release.html_url }}" >> message.txt

    # send message, @plebbit telegram chat id is -1234
    - name: "telegram notification"
      uses: appleboy/telegram-action@master
      with:
        to: 1986059725
        token: ${{ secrets.TELEGRAM_TOKEN }}
        disable_web_page_preview: true
        format: html
        message_file: message.txt
