# send notifications to telegram group on commits, releases, issues
name: notifications

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  push:
    # https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28#pushevent
    # if: ${{ github.event.type == 'PushEvent' }}
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event }}
    # @plebbit telegram chat id is -1001792656766
    - name: "telegram notifications"
      uses: appleboy/telegram-action@master
      with:
        to: 1986059725
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.commits[0].message }}

          by ${{ github.event.author.login }} in ${{ github.event.repository.name }}
          ${{ github.event.created_at }}
