# send notifications to telegram group on commits, releases, issues
# https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/contexts#github-context

name: notifications

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  push:
    # https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28#pushevent
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    matrix:
      commit: ${{ github.event.commits }}
    steps:
    - name: debug
      env:
        GITHUB_CONTEXT: ${{ toJSON(matrix.commit) }}
      run: echo "$GITHUB_CONTEXT"
    # @plebbit telegram chat id is -1234
    - name: "telegram notifications"
      uses: appleboy/telegram-action@master
      with:
        to: 1986059725
        token: ${{ secrets.TELEGRAM_TOKEN }}
        disable_web_page_preview: true
        format: html
        message: |
          <code>${{ matrix.commit.message }}</code>

          ${{ matrix.commit.timestamp }} by ${{ matrix.commit.author.username }} in ${{ github.repository }}
          ${{ matrix.commit.url }}
