# send notifications to telegram group on commits, releases, issues
# https://docs.github.com/en/enterprise-cloud@latest/actions/learn-github-actions/contexts#github-context

name: notifications

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  push:
    # https://docs.github.com/en/rest/overview/github-event-types?apiVersion=2022-11-28#pushevent
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
    - name: debug
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      run: echo "$GITHUB_CONTEXT"
    # @plebbit telegram chat id is -1234
    - name: "telegram notifications"
      uses: appleboy/telegram-action@master
      with:
        to: 1986059725
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.commits[0].message }}
          ${{ github.event.commits[0].author.name }}

          by ${{ github.actor }} in ${{ github.repository }}
          ${{ github.event.commits[0].author.name }}
