# send notifications to telegram group on commits, releases, issues
name: notifications

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
    # @plebbitjs telegram chat id is -1001792656766
    - name: "@plebbitjs telegram alert"
      uses: appleboy/telegram-action@master
      with:
        to: 1986059725
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.event.workflow_run.head_commit.message }}

          by ${{ github.event.workflow_run.head_commit.author.name }}
          ${{ github.event.workflow_run.head_commit.author.timestamp }}
          ${{ github.event.workflow_run.head_commit.author.url }}
