# docs https://github.com/marketplace/actions/create-release
# docs https://github.com/ncipollo/release-action

name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      # publish version release
      - run: echo "Progressive web app mirrors:\n- https://plebchan.eth.limo\n- https://plebchan.eth.link\n- https://cloudflare-ipfs.com/ipns/plebchan.eth (insecure, no subdomain isolation)\n\nCLI client:\n- https://github.com/plebbit/plebbit-cli/releases/latest$(cat changelog.txt)" > release-body.txt
      - run: cat release-body.txt
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'start.js'
          token: ${{ secrets.GITHUB_TOKEN }}
          replacesArtifacts: true
          bodyFile: "./release-body.txt"
          allowUpdates: true
