# docs https://github.com/marketplace/actions/create-release
# docs https://github.com/ncipollo/release-action

name: release

on: 
  push:
    tags:
      - 'v*'

jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

    # android build
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: yarn
    - run: yarn build
    - run: npx cap update
    - run: npx cap copy
    - run: cd android && gradle bundle
    - run: cd android && ./gradlew assembleRelease
    - run: mv android/app/build/outputs/apk/release/app-release-unsigned.apk dist/plebbit-$(node -e "console.log(require('./package.json').version)").apk
    - run: ls dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true

    # publish release 'latest'
    - uses: ncipollo/release-action@v1
      with:
        tag: latest
        artifacts: "dist/plebbit*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: true
        removeArtifacts: true
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true
