# docs https://github.com/marketplace/actions/create-release
# docs https://github.com/ncipollo/release-action

name: release

on: 
  push:
    tags:
      - 'v*'

jobs:
  android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: actions/setup-node@v2
      with:
        node-version: 16

    # build react app
    - run: yarn
    - run: yarn build

    # build apk
    - run: npx cap update
    - run: npx cap copy
    - run: cd android && gradle bundle
    - run: cd android && ./gradlew assembleRelease

    # sign apk
    - run: cd android/app/build/outputs/apk/release && jarsigner -keystore ../../../../../plebbit.keystore -storepass ${{ secrets.PLEBBIT_REACT_KEYSTORE_PASSWORD }} app-release-unsigned.apk plebbit && zipalign 4 app-release-unsigned.apk app-release.apk

    # move apk to dist folder
    - run: mv android/app/build/outputs/apk/release/app-release.apk dist/plebbit-$(node -e "console.log(require('./package.json').version)").apk
    - run: ls dist

    # publish version release
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/plebbit*.apk"
        token: ${{ secrets.GITHUB_TOKEN }}
        replacesArtifacts: false
        body: "Progressive web app mirrors:\n- https://demo.plebbit.eth.limo\n- https://demo.plebbit.eth.link\n- https://cloudflare-ipfs.com/ipns/demo.plebbit.eth"
        allowUpdates: true
